BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        id: 'input'
        TextInput:
            text: '34'
        BoxLayout:
            id: 'directions'
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        text: '54.717'
        color: (1, 1, 0, 1)