BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            id: user_input
            text: ''
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
        on_press: app.handle_conversion_to_km()
    Label:
        text: ''
        color: (1, 1, 0, 1)
        id: output_label